const users=[
    {
        id:2,
        name:"blanket",
        email:"dhanya@gmail.com",
        type:"admin"
    },
    {
        id:23,
        name:"bottle",
        email:"sri@gmail.com",
        type:"manager"
    },
    {
        id:5,
        name:"pen",
        email:"bfj@gmail.com",
        type:"user"
    },
    {
        id:4,
        name:"pencil",
        email:"ghjk@gmail.com",
        type:"admin"
    },
    {
        id:7,
        name:"book",
        email:"ugv@gmail.com",
        availability:"user"
    },
    {
        id:9,
        name:"band",
        email:"okn@gmail.com",
        availability:"manager"
    }
];
module.exports=users;